POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username":"soroush",
  "email":"soroush@yahoo.com",
  "password":"1234"
}

### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email":"soroush@yahoo.com",
  "password":"1234"
}

### refresh
POST http://localhost:3000/api/v1/auth/refresh

### logout
POST http://localhost:3000/api/v1/auth/logout


### getMe
GET http://localhost:3000/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWM2NGVlZDRkNDlmOTM4MWM5MmZjMGYiLCJpYXQiOjE3OTEzODEyODEsImV4cCI6MTc5MTM4MjE4MSwic3ViIjoiYWNjZXNzVG9rZW4ifQ.CvCgcyczTKbvQ_7Mr2GaGs6Xzy8RWHEcUEhzdd65KlE
